<<<<<<< HEAD
language: python
python:
  - 3.6
  - 3.7
  - 3.8
before_install:
  - python --version
  - pip install -U pip
  - pip install -U pytest
  - pip install codecov
install:
  - pip install ".[test]" . # install package + test dependencies
  - pip install -r requirements.txt
before_script:
  - export FLASK_APP="$TRAVIS_BUILD_DIR/app.py"
  - export FLASK_DEBUG=1
script: pytest # run tests
script: flask test
after_success:
  - codecov # submit coverage
>>>>>>> 4b6dfe2fe51374f7b426245998c906945dc2654e
