language: python

dist: xenial
before_install:
  - python --version
  - pip install -U pip
  - pip install -U pytest
  - pip install codecov
script:
  - pytest
after_success:
  - codecov # submit coverage