language: python

dist: xenial
before_install:
  - python --version
  - pip install -U pip
  - pip install -U pytest
  - pip install codecov
before_script:
  - export FLASK_APP="$TRAVIS_BUILD_DIR/app.py"
  - export FLASK_DEBUG=1
script: 
   - python -m pytest -v # run tests
   - flask test
after_success:
  - codecov # submit coverage
  